[package]
name = "safety-rust"
version = "0.1.0"
authors = ["Kendall Garner <17521368+kgarner7@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
chrono-tz = "0.5"
redis = "0.16.0"
serde = "1.0.114"
serenity = "0.8"
