[package]
name = "safety-rust"
version = "0.1.0"
authors = ["Kendall Garner <17521368+kgarner7@users.noreply.github.com>"]
edition = "2018"

[dependencies]
bincode = "1.3"
chrono = { version = "0.4", features = ["serde"] }
chrono-tz = "0.5"
lazy_static = "1.4.0"
parking_lot = "0.9.0"
rand = "0.7.0"
redis = "0.16.0"
regex = "1"
serde = { version = "1.0.114", features = ["derive"] }
serenity = "0.8"
uuid = { version = "0.8", features = ["serde", "v4"] }
